/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.awt.HeadlessException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Guillermo Veintemilla Clase que implementa la interfaz para poder
 * jugar a cada cliente
 */
public class InterfazJuego extends javax.swing.JFrame {

    final static String host = "127.0.0.1";
    final static int puerto = 4332;
    String palabra;
    String nombre;
    int errores = 0;
    int rondas = 0;
    private boolean acabado = false;
    private boolean perdido = false;

    /**
     * Creates new form InterfazJuego
     */
    public InterfazJuego(String palabra, String nombre) {
        this.palabra = palabra;
        this.nombre = nombre;
        JOptionPane.showMessageDialog(this, "¡¡Puedes cometer 5 errores, mucha suerte!!", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        labelNombreJugador.setText(nombre);
        mostrarLineas(palabra);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelNombreJugador = new javax.swing.JLabel();
        panelImagenes = new javax.swing.JPanel();
        labelEjecucion = new javax.swing.JLabel();
        panelJuego = new javax.swing.JPanel();
        panelLetras = new javax.swing.JPanel();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonC = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        botonE = new javax.swing.JButton();
        botonF = new javax.swing.JButton();
        botonG = new javax.swing.JButton();
        botonH = new javax.swing.JButton();
        botonI = new javax.swing.JButton();
        botonJ = new javax.swing.JButton();
        botonK = new javax.swing.JButton();
        botonL = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        botonN = new javax.swing.JButton();
        botonÑ = new javax.swing.JButton();
        botonO = new javax.swing.JButton();
        botonP = new javax.swing.JButton();
        botonQ = new javax.swing.JButton();
        botonR = new javax.swing.JButton();
        botonS = new javax.swing.JButton();
        botonT = new javax.swing.JButton();
        botonU = new javax.swing.JButton();
        botonV = new javax.swing.JButton();
        botonW = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        botonY = new javax.swing.JButton();
        botonZ = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelRondas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelErrores = new javax.swing.JLabel();
        panelPalabra = new javax.swing.JPanel();
        labelRaya1 = new javax.swing.JLabel();
        labelRaya2 = new javax.swing.JLabel();
        labelRaya3 = new javax.swing.JLabel();
        labelRaya4 = new javax.swing.JLabel();
        labelRaya5 = new javax.swing.JLabel();
        labelRaya6 = new javax.swing.JLabel();
        labelRaya7 = new javax.swing.JLabel();
        labelRaya8 = new javax.swing.JLabel();
        labelRaya9 = new javax.swing.JLabel();
        labelRaya10 = new javax.swing.JLabel();
        labelRaya11 = new javax.swing.JLabel();
        labelRaya12 = new javax.swing.JLabel();
        labelLetra3 = new javax.swing.JLabel();
        labelLetra1 = new javax.swing.JLabel();
        labelLetra2 = new javax.swing.JLabel();
        labelLetra4 = new javax.swing.JLabel();
        labelLetra6 = new javax.swing.JLabel();
        labelLetra5 = new javax.swing.JLabel();
        labelLetra9 = new javax.swing.JLabel();
        labelLetra8 = new javax.swing.JLabel();
        labelLetra7 = new javax.swing.JLabel();
        labelLetra10 = new javax.swing.JLabel();
        labelLetra11 = new javax.swing.JLabel();
        labelLetra12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        panelCabecera.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Juego del ejecutado -");

        labelNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNombreJugador.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addComponent(labelNombreJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelEjecucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.gif"))); // NOI18N
        labelEjecucion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panelImagenesLayout = new javax.swing.GroupLayout(panelImagenes);
        panelImagenes.setLayout(panelImagenesLayout);
        panelImagenesLayout.setHorizontalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagenesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEjecucion)
                .addContainerGap())
        );
        panelImagenesLayout.setVerticalGroup(
            panelImagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(labelEjecucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLetras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51), 3));

        botonA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonA.setText("A");
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });

        botonB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonB.setText("B");
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });

        botonC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonC.setText("C");
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });

        botonD.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonD.setText("D");
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });

        botonE.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonE.setText("E");
        botonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEActionPerformed(evt);
            }
        });

        botonF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonF.setText("F");
        botonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFActionPerformed(evt);
            }
        });

        botonG.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonG.setText("G");
        botonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGActionPerformed(evt);
            }
        });

        botonH.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonH.setText("H");
        botonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHActionPerformed(evt);
            }
        });

        botonI.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonI.setText("I");
        botonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIActionPerformed(evt);
            }
        });

        botonJ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonJ.setText("J");
        botonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJActionPerformed(evt);
            }
        });

        botonK.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonK.setText("K");
        botonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonKActionPerformed(evt);
            }
        });

        botonL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonL.setText("L");
        botonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLActionPerformed(evt);
            }
        });

        botonM.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonM.setText("M");
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });

        botonN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonN.setText("N");
        botonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNActionPerformed(evt);
            }
        });

        botonÑ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonÑ.setText("Ñ");
        botonÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonÑActionPerformed(evt);
            }
        });

        botonO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonO.setText("O");
        botonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOActionPerformed(evt);
            }
        });

        botonP.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonP.setText("P");
        botonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPActionPerformed(evt);
            }
        });

        botonQ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonQ.setText("Q");
        botonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQActionPerformed(evt);
            }
        });

        botonR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonR.setText("R");
        botonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRActionPerformed(evt);
            }
        });

        botonS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonS.setText("S");
        botonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSActionPerformed(evt);
            }
        });

        botonT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonT.setText("T");
        botonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTActionPerformed(evt);
            }
        });

        botonU.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonU.setText("U");
        botonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUActionPerformed(evt);
            }
        });

        botonV.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonV.setText("V");
        botonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVActionPerformed(evt);
            }
        });

        botonW.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonW.setText("W");
        botonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonWActionPerformed(evt);
            }
        });

        botonX.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonX.setText("X");
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });

        botonY.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonY.setText("Y");
        botonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYActionPerformed(evt);
            }
        });

        botonZ.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonZ.setText("Z");
        botonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLetrasLayout = new javax.swing.GroupLayout(panelLetras);
        panelLetras.setLayout(panelLetrasLayout);
        panelLetrasLayout.setHorizontalGroup(
            panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLetrasLayout.createSequentialGroup()
                        .addComponent(botonM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLetrasLayout.createSequentialGroup()
                        .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLetrasLayout.createSequentialGroup()
                                .addComponent(botonA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLetrasLayout.createSequentialGroup()
                                .addComponent(botonG, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLetrasLayout.createSequentialGroup()
                                .addComponent(botonR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonS, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonU, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonW, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLetrasLayout.createSequentialGroup()
                                .addComponent(botonX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelLetrasLayout.setVerticalGroup(
            panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLetrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonB, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonG, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonH, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonJ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonK, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonO, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonQ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonS, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonU, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonW, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLetrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonY, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonZ, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Rondas:");

        labelRondas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelRondas.setForeground(new java.awt.Color(0, 204, 0));
        labelRondas.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Errores:");

        labelErrores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelErrores.setForeground(new java.awt.Color(255, 0, 0));
        labelErrores.setText("0");

        javax.swing.GroupLayout panelJuegoLayout = new javax.swing.GroupLayout(panelJuego);
        panelJuego.setLayout(panelJuegoLayout);
        panelJuegoLayout.setHorizontalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRondas)
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelErrores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelJuegoLayout.setVerticalGroup(
            panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJuegoLayout.createSequentialGroup()
                .addComponent(panelLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelRondas)
                    .addComponent(jLabel4)
                    .addComponent(labelErrores))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        labelRaya1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya1.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya1.setText("____");
        labelRaya1.setVisible(false);

        labelRaya2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya2.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya2.setText("____");
        labelRaya2.setVisible(false);

        labelRaya3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya3.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya3.setText("____");
        labelRaya3.setVisible(false);

        labelRaya4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya4.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya4.setText("____");
        labelRaya4.setVisible(false);

        labelRaya5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya5.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya5.setText("____");
        labelRaya5.setVisible(false);

        labelRaya6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya6.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya6.setText("____");
        labelRaya6.setVisible(false);

        labelRaya7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya7.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya7.setText("____");
        labelRaya7.setVisible(false);

        labelRaya8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya8.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya8.setText("____");
        labelRaya8.setVisible(false);

        labelRaya9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya9.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya9.setText("____");
        labelRaya9.setVisible(false);

        labelRaya10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya10.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya10.setText("____");
        labelRaya10.setVisible(false);

        labelRaya11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya11.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya11.setText("____");
        labelRaya11.setVisible(false);

        labelRaya12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelRaya12.setForeground(new java.awt.Color(255, 51, 51));
        labelRaya12.setText("____");
        labelRaya12.setVisible(false);

        labelLetra3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelLetra12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelLetra12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelPalabraLayout = new javax.swing.GroupLayout(panelPalabra);
        panelPalabra.setLayout(panelPalabraLayout);
        panelPalabraLayout.setHorizontalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPalabraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRaya1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(labelLetra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRaya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLetra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLetra3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRaya3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLetra4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRaya4, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLetra5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRaya5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLetra6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelRaya6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelRaya7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLetra7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(labelRaya8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRaya9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRaya10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPalabraLayout.createSequentialGroup()
                        .addComponent(labelLetra8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLetra9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLetra10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLetra11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRaya11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRaya12)
                    .addComponent(labelLetra12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelPalabraLayout.setVerticalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPalabraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLetra6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelLetra1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelLetra2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelLetra4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRaya1)
                    .addComponent(labelRaya2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRaya4)
                    .addComponent(labelRaya6)
                    .addComponent(labelRaya7)
                    .addComponent(labelRaya8)
                    .addComponent(labelRaya9)
                    .addComponent(labelRaya10)
                    .addComponent(labelRaya11)
                    .addComponent(labelRaya3)
                    .addComponent(labelRaya12)
                    .addComponent(labelRaya5)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelPalabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(panelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
        comportamientoBoton("A");
        botonA.setEnabled(false);
    }//GEN-LAST:event_botonAActionPerformed

    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
        comportamientoBoton("B");
        botonB.setEnabled(false);
    }//GEN-LAST:event_botonBActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        comportamientoBoton("C");
        botonC.setEnabled(false);
    }//GEN-LAST:event_botonCActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
        comportamientoBoton("D");
        botonD.setEnabled(false);
    }//GEN-LAST:event_botonDActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEActionPerformed
        comportamientoBoton("E");
        botonE.setEnabled(false);
    }//GEN-LAST:event_botonEActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFActionPerformed
        comportamientoBoton("F");
        botonF.setEnabled(false);
    }//GEN-LAST:event_botonFActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGActionPerformed
        comportamientoBoton("G");
        botonG.setEnabled(false);
    }//GEN-LAST:event_botonGActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHActionPerformed
        comportamientoBoton("H");
        botonH.setEnabled(false);
    }//GEN-LAST:event_botonHActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIActionPerformed
        comportamientoBoton("I");
        botonI.setEnabled(false);
    }//GEN-LAST:event_botonIActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJActionPerformed
        comportamientoBoton("J");
        botonJ.setEnabled(false);
    }//GEN-LAST:event_botonJActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonKActionPerformed
        comportamientoBoton("K");
        botonK.setEnabled(false);
    }//GEN-LAST:event_botonKActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLActionPerformed
        comportamientoBoton("L");
        botonL.setEnabled(false);
    }//GEN-LAST:event_botonLActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
        comportamientoBoton("M");
        botonM.setEnabled(false);
    }//GEN-LAST:event_botonMActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNActionPerformed
        comportamientoBoton("N");
        botonN.setEnabled(false);
    }//GEN-LAST:event_botonNActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonÑActionPerformed
        comportamientoBoton("Ñ");
        botonÑ.setEnabled(false);
    }//GEN-LAST:event_botonÑActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOActionPerformed
        comportamientoBoton("O");
        botonO.setEnabled(false);
    }//GEN-LAST:event_botonOActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPActionPerformed
        comportamientoBoton("P");
        botonP.setEnabled(false);
    }//GEN-LAST:event_botonPActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQActionPerformed
        comportamientoBoton("Q");
        botonQ.setEnabled(false);
    }//GEN-LAST:event_botonQActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRActionPerformed
        comportamientoBoton("R");
        botonR.setEnabled(false);
    }//GEN-LAST:event_botonRActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSActionPerformed
        comportamientoBoton("S");
        botonS.setEnabled(false);
    }//GEN-LAST:event_botonSActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTActionPerformed
        comportamientoBoton("T");
        botonT.setEnabled(false);
    }//GEN-LAST:event_botonTActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUActionPerformed
        comportamientoBoton("U");
        botonU.setEnabled(false);
    }//GEN-LAST:event_botonUActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVActionPerformed
        comportamientoBoton("V");
        botonV.setEnabled(false);
    }//GEN-LAST:event_botonVActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonWActionPerformed
        comportamientoBoton("W");
        botonW.setEnabled(false);
    }//GEN-LAST:event_botonWActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed
        comportamientoBoton("X");
        botonX.setEnabled(false);
    }//GEN-LAST:event_botonXActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYActionPerformed
        comportamientoBoton("Y");
        botonY.setEnabled(false);
    }//GEN-LAST:event_botonYActionPerformed
    /**
     * Boton para comprobar si la letra esta en la palabra
     *
     * @param evt
     */
    private void botonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonZActionPerformed
        comportamientoBoton("Z");
        botonZ.setEnabled(false);
    }//GEN-LAST:event_botonZActionPerformed

    /**
     * Metodo que comprueba si la letra pertenece o no a la palabra
     * @param letra
     * @throws HeadlessException 
     */
    public void comportamientoBoton(String letra) throws HeadlessException {
        if (!introducirLetra(letra)) {
            errores++;
            cambiarLabel();
            JOptionPane.showMessageDialog(this, "Has fallado", "Fallo", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Letra introducida", "Acierto", JOptionPane.INFORMATION_MESSAGE);
        }
        rondas++;
        labelErrores.setText(String.valueOf(errores));
        labelRondas.setText(String.valueOf(rondas));
        Socket miJugador;
        DataOutputStream output;
        DataInputStream input;
        try {
            miJugador = new Socket(host, puerto);
            output = new DataOutputStream(miJugador.getOutputStream());
            input = new DataInputStream(miJugador.getInputStream());
            output.writeInt(1);
            output.writeUTF(nombre);
            output.writeInt(rondas);
            output.writeInt(errores);
            for (int i = 0; i < palabra.length(); i++) {
                if (seleccionarLabel(i).getText().contentEquals("")) {
                    setAcabado(false);
                    break;
                } else {
                    setAcabado(true);
                }
            }
            if (isAcabado() || isPerdido()) {
                //InterfazEsperar ie = new InterfazEsperar();
                output.writeBoolean(true);
                setEnabled(false);
                input.readInt();
                if (input.readUTF().contentEquals(nombre)) {
                    //ie.dispose();
                    dispose();
                    InterfazGanador ig = new InterfazGanador();
                } else {
                    //ie.dispose();
                    dispose();
                    InterfazPerdido ip = new InterfazPerdido();
                }
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No puedes conectarte al servidor");
        }
    }

    /**
     * Metodo que devuelve true si ha metido la letra en un label
     * @param letra
     * @return 
     */
    public boolean introducirLetra(String letra) {
        boolean introduce = false;
        for (int i = 0; i < palabra.length(); i++) {
            if (palabra.charAt(i) == letra.charAt(0)) {
                seleccionarLabel(i).setText(String.valueOf(letra));
                introduce = true;
            }
        }
        return introduce;
    }

    /**
     * Metodo para cambiar la imagen del ejecutado si has fallado
     */
    public void cambiarLabel() {
        switch (errores) {
            case 0:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\1.gif"));
                break;
            case 1:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\2.gif"));
                break;
            case 2:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\3.gif"));
                break;
            case 3:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\4.gif"));
                break;
            case 4:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\5.gif"));
                break;
            case 5:
                labelEjecucion.setIcon(new javax.swing.ImageIcon("imagenes\\6.gif"));
                setPerdido(true);
                break;
        }
    }

    /**
     * Metodo para seleccionar el label de la letra qeu corresponde
     * @param indice
     * @return 
     */
    public JLabel seleccionarLabel(int indice) {
        switch (indice) {
            case 0:
                return labelLetra1;
            case 1:
                return labelLetra2;
            case 2:
                return labelLetra3;
            case 3:
                return labelLetra4;
            case 4:
                return labelLetra5;
            case 5:
                return labelLetra6;
            case 6:
                return labelLetra7;
            case 7:
                return labelLetra8;
            case 8:
                return labelLetra9;
            case 9:
                return labelLetra10;
            case 10:
                return labelLetra11;
        }
        return labelLetra12;
    }

    /**
     * Metodo para mostrar la dimension de la palabra con rayas
     * @param palabra 
     */
    public void mostrarLineas(String palabra) {
        int dimension = palabra.length();
        if (dimension == 4) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
        }
        if (dimension == 5) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
        }
        if (dimension == 6) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
        }
        if (dimension == 7) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
        }
        if (dimension == 8) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
            labelRaya8.setVisible(true);
        }
        if (dimension == 9) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
            labelRaya8.setVisible(true);
            labelRaya9.setVisible(true);
        }
        if (dimension == 10) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
            labelRaya8.setVisible(true);
            labelRaya9.setVisible(true);
            labelRaya10.setVisible(true);
        }
        if (dimension == 11) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
            labelRaya8.setVisible(true);
            labelRaya9.setVisible(true);
            labelRaya10.setVisible(true);
            labelRaya11.setVisible(true);
        }
        if (dimension == 12) {
            labelRaya1.setVisible(true);
            labelRaya2.setVisible(true);
            labelRaya3.setVisible(true);
            labelRaya4.setVisible(true);
            labelRaya5.setVisible(true);
            labelRaya6.setVisible(true);
            labelRaya7.setVisible(true);
            labelRaya8.setVisible(true);
            labelRaya9.setVisible(true);
            labelRaya10.setVisible(true);
            labelRaya11.setVisible(true);
            labelRaya12.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonD;
    private javax.swing.JButton botonE;
    private javax.swing.JButton botonF;
    private javax.swing.JButton botonG;
    private javax.swing.JButton botonH;
    private javax.swing.JButton botonI;
    private javax.swing.JButton botonJ;
    private javax.swing.JButton botonK;
    private javax.swing.JButton botonL;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonN;
    private javax.swing.JButton botonO;
    private javax.swing.JButton botonP;
    private javax.swing.JButton botonQ;
    private javax.swing.JButton botonR;
    private javax.swing.JButton botonS;
    private javax.swing.JButton botonT;
    private javax.swing.JButton botonU;
    private javax.swing.JButton botonV;
    private javax.swing.JButton botonW;
    private javax.swing.JButton botonX;
    private javax.swing.JButton botonY;
    private javax.swing.JButton botonZ;
    private javax.swing.JButton botonÑ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelEjecucion;
    private javax.swing.JLabel labelErrores;
    private javax.swing.JLabel labelLetra1;
    private javax.swing.JLabel labelLetra10;
    private javax.swing.JLabel labelLetra11;
    private javax.swing.JLabel labelLetra12;
    private javax.swing.JLabel labelLetra2;
    private javax.swing.JLabel labelLetra3;
    private javax.swing.JLabel labelLetra4;
    private javax.swing.JLabel labelLetra5;
    private javax.swing.JLabel labelLetra6;
    private javax.swing.JLabel labelLetra7;
    private javax.swing.JLabel labelLetra8;
    private javax.swing.JLabel labelLetra9;
    private javax.swing.JLabel labelNombreJugador;
    private javax.swing.JLabel labelRaya1;
    private javax.swing.JLabel labelRaya10;
    private javax.swing.JLabel labelRaya11;
    private javax.swing.JLabel labelRaya12;
    private javax.swing.JLabel labelRaya2;
    private javax.swing.JLabel labelRaya3;
    private javax.swing.JLabel labelRaya4;
    private javax.swing.JLabel labelRaya5;
    private javax.swing.JLabel labelRaya6;
    private javax.swing.JLabel labelRaya7;
    private javax.swing.JLabel labelRaya8;
    private javax.swing.JLabel labelRaya9;
    private javax.swing.JLabel labelRondas;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelImagenes;
    private javax.swing.JPanel panelJuego;
    private javax.swing.JPanel panelLetras;
    private javax.swing.JPanel panelPalabra;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the acabado
     */
    public boolean isAcabado() {
        return acabado;
    }

    /**
     * @param acabado the acabado to set
     */
    public void setAcabado(boolean acabado) {
        this.acabado = acabado;
    }

    /**
     * @return the perdido
     */
    public boolean isPerdido() {
        return perdido;
    }

    /**
     * @param perdido the perdido to set
     */
    public void setPerdido(boolean perdido) {
        this.perdido = perdido;
    }

    /**
     * Metodo main de la interfaz
     * @param args
     * @throws ClassNotFoundException
     * @throws InterruptedException 
     */
    public static void main(String[] args) throws ClassNotFoundException, InterruptedException {
        try {
            Socket miJugador = new Socket(host, puerto);
            DataOutputStream output = new DataOutputStream(miJugador.getOutputStream());
            DataInputStream input = new DataInputStream(miJugador.getInputStream());
            InterfazNombre in = new InterfazNombre();
            while (!in.isPulsado()) {
                System.out.println("");
            }
            output.writeInt(0);
            if (input.readBoolean()) {
                JOptionPane.showMessageDialog(null, "La partida ya ha comenzado");
            } else {
                output.writeUTF(in.getjTextField1().getText());
                String palabra = input.readUTF();
                InterfazJuego ij = new InterfazJuego(palabra, in.getjTextField1().getText());
                ij.setVisible(true);
                ij.setEnabled(false);
                input.readInt();
                ij.setEnabled(true);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No puedes conectarte al servidor");
        }
    }
}
